name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: Testing.sln                        # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
    - name: Run vstests
      uses: microsoft/vstest-action@v1.0.0
      with:
        testAssembly: TestProject.dll
        searchFolder: .\TestProject\bin\Debug\
        runInParallel: true

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
