name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        
    runs-on: windows-latest  

    env:
      Solution_Name: Testing.sln 

    steps: 
    - name: Execute unit tests
      run: dotnet test
